### PR TITLE
CI examples

### PR DESCRIPTION
**Pull request by renefritze**
This includes the cpp examples.

Building them however fails. Please have a look @ftschindler 
[gdt.txt](https://github.com/dune-gdt/dune-merged/files/9829817/gdt.txt)

### CODE REVIEW

**Comment by renefritze** [comment]
To hook the python examples into cmake I've added installing from a requirements file as a dependency. I've tried to set the pymor version in it to what was current in 2019. However that pymor does not install with python 3.10. With current pymor at least the imports have hanged. Please change as needed @ftschindler

**Comment by ftschindler** [comment]
> 

Very nice, thx. Actual errors, ouch :/

**Comment by ftschindler** [comment]
> To hook the python examples into cmake I've added installing from a requirements file as a dependency. I've tried to set the pymor version in it to what was current in 2019. However that pymor does not install with python 3.10. With current pymor at least the imports have hanged. Please change as needed @ftschindler

That hooking is somewhere else, though? Will look into it!

**Comment by renefritze** [comment]
> > To hook the python examples into cmake I've added installing from a requirements file as a dependency. I've tried to set the pymor version in it to what was current in 2019. However that pymor does not install with python 3.10. With current pymor at least the imports have hanged. Please change as needed @ftschindler
> 
> That hooking is somewhere else, though? Will look into it!

Uhm, looks like I forgot to push that bit, actually. Will do come monday.

**Comment by renefritze** [comment]
> > > To hook the python examples into cmake I've added installing from a requirements file as a dependency. I've tried to set the pymor version in it to what was current in 2019. However that pymor does not install with python 3.10. With current pymor at least the imports have hanged. Please change as needed @ftschindler
> > 
> > 
> > That hooking is somewhere else, though? Will look into it!
> 
> Uhm, looks like I forgot to push that bit, actually. Will do come monday.

Tuesday is almost Monday :)

3104eced0b9666bf9ccfcf16ab582a87d85399ed

**Comment by ftschindler** [comment]
> > > > To hook the python examples into cmake I've added installing from a requirements file as a dependency. I've tried to set the pymor version in it to what was current in 2019. However that pymor does not install with python 3.10. With current pymor at least the imports have hanged. Please change as needed @ftschindler
> > > 
> > > 
> > > That hooking is somewhere else, though? Will look into it!
> > 
> > 
> > Uhm, looks like I forgot to push that bit, actually. Will do come monday.
> 
> Tuesday is almost Monday :)
> 
> [3104ece](https://github.com/dune-gdt/dune-merged/commit/3104eced0b9666bf9ccfcf16ab582a87d85399ed)

As good a Monday as it will get :) Looks good, hopefully we'll not require different pymor versions for different examples over time :/

**Comment by renefritze** [comment]
We really need to move the whole merge forward @ftschindler. Did you have a look at the examples?

**Comment by ftschindler** [comment]
> We really need to move the whole merge forward @ftschindler. Did you have a look at the examples?

no, sry. I'll put it in for this week!

**Comment by renefritze** [comment]
I'll have to rebase this on main now.

**Comment by ftschindler** [comment]
I'll look into this next then

**Comment by renefritze** [comment]
You're already looking into the example over [here](url) btw/ :wink:

**Pull request merged**
