### PR TITLE
ci tutorials

### LINKED ISSUE #34: Website and tutorial deploy
Looks like I didn't carry this over from gitlab at all yet.

### PR DESCRIPTION
**Pull request by renefritze**
- [cmake] integrate sphinx building into cmake
- [git] ignore generated vtus
- [cmake] also install viz packages for infra extra
- [tutorials] fix deprecated sphinx config options

closes #34

### CODE REVIEW

**Comment by renefritze** [comment]
@ftschindler failures in the tutorials execution need fixing. Look similiar to examples

**Comment by renefritze** [comment]
Visualizations are seem broken in HTML output :disappointed:

**Comment by ftschindler** [comment]
> Visualizations seem broken in HTML output disappointed

As in a failure? Cause we never got any output in the rendered tutorials, which was fine for us for the moment...

**Comment by renefritze** [comment]
> > Visualizations seem broken in HTML output disappointed
> 
> As in a failure? Cause we never got any output in the rendered tutorials, which was fine for us for the moment...

Ah, in that case everything's fine :see_no_evil: 
I did not remember that at all.

**Pull request merged**
