### PR TITLE
un-vendor pybind11

### PR DESCRIPTION
**Pull request by renefritze**
- remove vendored pybind11
- add pybind11 back as a submodule
- switch include path for pybind11 files
- [cmake] rewire pybind11 usage
- [cmake] bring back the bindings target
- bump pybind11 to v2.10

### CODE REVIEW

**Comment by renefritze** [comment]
Important to note @dune-gdt/all: 45ccf572456846deabaf34f5fa1710ed010294c3

**Comment by ftschindler** [comment]
Nice one in general. Did you have a green CI before the bump?

**Comment by renefritze** [comment]
> Nice one in general. Did you have a green CI before the bump?

? You mean on main?

**Comment by ftschindler** [comment]
No, I was asking if the version bump gave any trouble. Did not look like it, though :)

**Comment by renefritze** [comment]
Ah, no. Actually no CI ran pre-bump on this branch.

**Pull request merged**
