### PR TITLE
CI Setup and Consolidation Merge

### PR DESCRIPTION
**Pull request by renefritze**
This mostly equivalent to https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-merged/-/merge_requests/1 plus https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-merged/-/merge_requests/2 plus github CI setup

### CODE REVIEW

**Comment by renefritze** [comment]
> I will have to rebase and force push this branch since [05defe9](https://github.com/dune-gdt/dune-merged/commit/05defe952e2497cd74821f8c6f6a0e7fba10a853) not being squashed yet and failing the commit check

That's done and we can now expect a nice all green in a bit :sweat_smile:

**Comment by renefritze** [comment]
Yeah, [no](https://github.com/dune-gdt/dune-merged/actions/runs/3683459403/jobs/6232066553#step:5:2063).

**Comment by renefritze** [comment]
> Yeah, [no](https://github.com/dune-gdt/dune-merged/actions/runs/3683459403/jobs/6232066553#step:5:2063).

This a weird one. The rebase lead to git describe not finding tags on github. There are now a bunch of dummy tags I made while figuring this out. Apparently the default checkout action does not (always) fetch tags, so there's another step in the workflows for that now.

**Comment by renefritze** [comment]
From POV this can me merged now. The publish failure is OK, since I pushed the commit that was tagged only after the pipeline for the tag had already run.

**Review by ftschindler — APPROVED** [review]
Lets get this in. Is the `.ci/gitlab/` folder still in use somehow, or could we drop it?

**Comment by renefritze** [comment]
> Lets get this in. Is the `.ci/gitlab/` folder still in use somehow, or could we drop it?

I'm re-using scripts from there. Let's clean that up in separate PR.

**Pull request merged**
